CREATE TABLE IF NOT EXISTS process_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_name VARCHAR(255) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    process_id BIGINT NOT NULL CHECK (process_id >= 0),
    process_name VARCHAR(512) NOT NULL,
    cpu_usage_percent DOUBLE PRECISION NOT NULL CHECK (cpu_usage_percent >= 0 AND cpu_usage_percent <= 100),
    memory_bytes BIGINT NOT NULL CHECK (memory_bytes >= 0),
    memory_usage_percent DOUBLE PRECISION NOT NULL CHECK (memory_usage_percent >= 0 AND memory_usage_percent <= 100)
);

CREATE INDEX IF NOT EXISTS idx_process_metrics_host_collected_at
    ON process_metrics (host_name, collected_at DESC);

CREATE INDEX IF NOT EXISTS idx_process_metrics_process_collected_at
    ON process_metrics (process_id, collected_at DESC);
