CREATE TABLE IF NOT EXISTS host_metric_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_name VARCHAR(255) NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    cpu_usage_percent DOUBLE PRECISION NOT NULL CHECK (cpu_usage_percent >= 0 AND cpu_usage_percent <= 100),
    memory_usage_percent DOUBLE PRECISION NOT NULL CHECK (memory_usage_percent >= 0 AND memory_usage_percent <= 100),
    disk_usage_percent DOUBLE PRECISION NOT NULL CHECK (disk_usage_percent >= 0 AND disk_usage_percent <= 100),
    CONSTRAINT uq_host_metric_snapshots_host_collected_at UNIQUE (host_name, collected_at)
);

CREATE INDEX IF NOT EXISTS idx_host_metric_snapshots_host_collected_at
    ON host_metric_snapshots (host_name, collected_at DESC);
